include missing sys/types.h
Fixes errors seen on musl
pqueue.h:21:3: error: unknown type name 'u_int32_t'

Signed-off-by: Khem Raj <raj.khem@gmail.com>